Repository cloudfoundry/cf-acceptance-tests, pull requests merged in 2019-04, with the labels that each got.

#367 Remove `include_assisted_credhub` from ex. config
  example-cats-config.json
Labels: scheduled

#370 assets/nora: Doc on how to build
  assets/nora/README.md
  assets/nora/bin/BreakoutBomb.exe
  assets/nora/bin/JobBreakoutTest.exe
  assets/nora/bin/mmapleak.exe
Labels: in progress

#366 Use cf tail --envelope-class flag to only get logs in logs helper
  helpers/logs/logs_helper.go
Labels: unscheduled

#374 fix container metrics regex to accomodate apps with less memory
  apps/lifecycle.go
Labels: in progress
