Repository cloudfoundry/cf-acceptance-tests, pull requests merged in 2019-11, with the labels that each got.

#389 assets/nora: Add info to Readme
  assets/nora/README.md
Labels: delivered

#392 Revert "Randomize the shared domain created by this spec"
  volume_services/volume_services.go
Labels: in progress

#395 Revert "Randomize the shared domain created by this spec"
  volume_services/volume_services.go
Labels: scheduled
