Repository cloudfoundry/cf-acceptance-tests, pull requests merged in 2019-10, with the labels that each got.

#388 `bin/test` requires Go 1.11
  README.md
Labels: in progress

#390 Ensure test creates the shared domains that it requires
  volume_services/volume_services.go
Labels: scheduled

#391 cleanup + improve volume service tests against flakes
  volume_services/volume_services.go
Labels: unscheduled
